import React from 'react'
import Head from 'next/head'
import Image  from 'next/image'
const index = () => {
  return (
    <div className="bg-black w-full h-full">
    <Head>
      <title>PROVERZE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/img/proverze.svg" />
    </Head>
      
      <main className='h-[540px] w-full flex justify-center items-center bg-black'>
       <Image width={180} height={180} src="/img/proverze.svg" alt="proverze"/>
        
      </main>
      
      <footer>
     
      </footer>
      
     
      
    
    
  </div>
  )
}

export default index