import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header'
import Footer from '../../components/Footer'
import Email from '../../components/email/Email'
const index = () => {
  return (
    <div className="bg-white1 w-full h-full">
      <Head>
        <title>landing - comprar ahora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
        <main className='overflow-y-auto'>
         <Email/>
          
        </main>
        
        <footer>
       
        </footer>
        
       
        
      
      
    </div>
  )
}

export default index